
mySpring: 
  jms:
    username: JMS Username$$yml
    password: somepass$$yml
    url: SomeURL$$yml
    
---
spring: 
  profiles: de
mySpring: 
  jms:
    username: JMS Username$$$German
